# Machine parameters
nodes = [
  { :hostname => 'LABSQL01', :box => 'unpatched-win2k12r2', :cpus => '2', :maxmemory => '4096'}
]
vSwitch =  "vExternal"


#def provision_chocolatey(config)
#    config.vm.provision "shell" do  |script|
#        script.name = "Install Chocolatey"
#        script.inline = "iex ((new-object net.webclient).DownloadString('https://chocolatey.org/install.ps1'))"
#        script.privileged = false
#    end
#end

#system("
#      cmd /c powershell.exe -noprofile -file ../scripts/Set-GuestIP.ps1
#")

# Vagrant configuration (file format v2)
Vagrant.configure("2") do |config|

  config.winrm.username = 'vagrant'
  config.winrm.password = "vagrant" 

  nodes.each do |node|
    # machine to base off
    config.vm.box = node[:box]

    # disabled shared folders
    config.vm.synced_folder ".", "/vagrant", disabled: true

    # set the vSwitch to use
    config.vm.network "public_network", bridge: "vExternal"

    # hyper-v specifics, see 	https://www.vagrantup.com/docs/hyperv/configuration.html
    config.vm.provider "hyperv" do |h|
        h.vmname = node[:hostname]
        h.cpus = node[:cpus]
        # maxmemory is the maximum allowed via dynamic allocation
        h.maxmemory = node[:maxmemory]
        h.differencing_disk = true
        h.auto_start_action = "Nothing"
        h.auto_stop_action = "TurnOff"
        h.ip_address_timeout = 600
    end

    # copy and run provisioning scripts
    # - tracking scheduled task issue - https://github.com/hashicorp/vagrant/issues/9138
    config.vm.provision "file", source: "./scripts", destination: "C:/tmp/"

    config.vm.provision "shell", inline: "C:/tmp/scripts/001-Invoke-Scripts.ps1"
    
    # do a reboot
    config.vm.provision :reload
    
    # install modules
    config.vm.provision "shell", inline: "C:/tmp/scripts/002-Invoke-Scripts.ps1", privileged: false

    #provision_chocolatey(config)
    
  end

end